package group.mondi.web.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "Employees", schema = "dbo", catalog = "SLPKContacts_test_5")
public class Employee {

	private String id;
	private long source;
	private long personalNumberId;
	private Long departmentId;
	private Long positionId;
	private String lastName;
	private String lastNameEnglish;
	private String firstName;
	private String firstNameEnglish;
	private String middleName;
	private Date absentStartDate;
	private Date absentEndDate;
	private Long absentPersonNumber1;
	private Long absentPersonNumber2;
	private Long absentPersonNumber3;
	private Integer whoLastModifiedPhoto;
	private String email;
	private String mobile1;
	private String mobile2;
	private String phoneInt;
	private String phoneExt;
	private String pager;
	private String mobileCorp;
	private String fax;
	private String internet;
	private String r3access;
	private String garant;
	private String domainName;
	private String bwaccess;
	private String modem;
	private String hrrupaccess;
	private String emailPrivate;
	private String fp3access;
	private String fw3access;
	private String statePositionText;
	private String orgUnityText;
	private String searchContentField;
	private long uid;
	private String absentName;
	private Integer lastModifiedSource;
	private Date lastModified;
	private String photoName;
	private Boolean isDeleted;
	private Integer saved;

	public Employee() {
	}

	public Employee(long source, long personalNumberId, String lastName, String firstName,
			String middleName, long uid) {
		this.source = source;
		this.personalNumberId = personalNumberId;
		this.lastName = lastName;
		this.firstName = firstName;
		this.middleName = middleName;
		this.uid = uid;
	}

	public Employee(long source, long personalNumberId, Long departmentId, Long positionId, String lastName,
			String lastNameEnglish, String firstName, String firstNameEnglish,
			String middleName, Date absentStartDate, Date absentEndDate, Long absentPersonNumber1,
			Long absentPersonNumber2, Long absentPersonNumber3, Integer whoLastModifiedPhoto, String email,
			String mobile1, String mobile2, String phoneInt, String phoneExt,
			String pager, String mobileCorp, String fax, String internet, String r3access,
			String garant, String domainName, String bwaccess, String modem,
			String hrrupaccess, String emailPrivate, String fp3access, String fw3access,
			String statePositionText, String orgUnityText, String searchContentField, long uid,
			String absentName, Integer lastModifiedSource, Date lastModified, String photoName,
			Boolean isDeleted, Integer saved) {
		this.source = source;
		this.personalNumberId = personalNumberId;
		this.departmentId = departmentId;
		this.positionId = positionId;
		this.lastName = lastName;
		this.lastNameEnglish = lastNameEnglish;
		this.firstName = firstName;
		this.firstNameEnglish = firstNameEnglish;
		this.middleName = middleName;
		this.absentStartDate = absentStartDate;
		this.absentEndDate = absentEndDate;
		this.absentPersonNumber1 = absentPersonNumber1;
		this.absentPersonNumber2 = absentPersonNumber2;
		this.absentPersonNumber3 = absentPersonNumber3;
		this.whoLastModifiedPhoto = whoLastModifiedPhoto;
		this.email = email;
		this.mobile1 = mobile1;
		this.mobile2 = mobile2;
		this.phoneInt = phoneInt;
		this.phoneExt = phoneExt;
		this.pager = pager;
		this.mobileCorp = mobileCorp;
		this.fax = fax;
		this.internet = internet;
		this.r3access = r3access;
		this.garant = garant;
		this.domainName = domainName;
		this.bwaccess = bwaccess;
		this.modem = modem;
		this.hrrupaccess = hrrupaccess;
		this.emailPrivate = emailPrivate;
		this.fp3access = fp3access;
		this.fw3access = fw3access;
		this.statePositionText = statePositionText;
		this.orgUnityText = orgUnityText;
		this.searchContentField = searchContentField;
		this.uid = uid;
		this.absentName = absentName;
		this.lastModifiedSource = lastModifiedSource;
		this.lastModified = lastModified;
		this.photoName = photoName;
		this.isDeleted = isDeleted;
		this.saved = saved;
	}

	@GenericGenerator(name = "com.mondigroup.web.model.EmployeesIdGenerator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "com.mondigroup.web.model.EmployeesIdGenerator")

	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Source", nullable = false)
	public long getSource() {
		return this.source;
	}

	public void setSource(long source) {
		this.source = source;
	}

	@Column(name = "PersonalNumberID", nullable = false)
	public long getPersonalNumberId() {
		return this.personalNumberId;
	}

	public void setPersonalNumberId(long personalNumberId) {
		this.personalNumberId = personalNumberId;
	}

	@Column(name = "DepartmentID")
	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "PositionID")
	public Long getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Long positionId) {
		this.positionId = positionId;
	}

	@Column(name = "LastName", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "LastNameEnglish")
	public String getLastNameEnglish() {
		return this.lastNameEnglish;
	}

	public void setLastNameEnglish(String lastNameEnglish) {
		this.lastNameEnglish = lastNameEnglish;
	}

	@Column(name = "FirstName", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "FirstNameEnglish")
	public String getFirstNameEnglish() {
		return this.firstNameEnglish;
	}

	public void setFirstNameEnglish(String firstNameEnglish) {
		this.firstNameEnglish = firstNameEnglish;
	}

	@Column(name = "MiddleName", nullable = false)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AbsentStartDate", length = 10)
	public Date getAbsentStartDate() {
		return this.absentStartDate;
	}

	public void setAbsentStartDate(Date absentStartDate) {
		this.absentStartDate = absentStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AbsentEndDate", length = 10)
	public Date getAbsentEndDate() {
		return this.absentEndDate;
	}

	public void setAbsentEndDate(Date absentEndDate) {
		this.absentEndDate = absentEndDate;
	}

	@Column(name = "AbsentPersonNumber1")
	public Long getAbsentPersonNumber1() {
		return this.absentPersonNumber1;
	}

	public void setAbsentPersonNumber1(Long absentPersonNumber1) {
		this.absentPersonNumber1 = absentPersonNumber1;
	}

	@Column(name = "AbsentPersonNumber2")
	public Long getAbsentPersonNumber2() {
		return this.absentPersonNumber2;
	}

	public void setAbsentPersonNumber2(Long absentPersonNumber2) {
		this.absentPersonNumber2 = absentPersonNumber2;
	}

	@Column(name = "AbsentPersonNumber3")
	public Long getAbsentPersonNumber3() {
		return this.absentPersonNumber3;
	}

	public void setAbsentPersonNumber3(Long absentPersonNumber3) {
		this.absentPersonNumber3 = absentPersonNumber3;
	}

	@Column(name = "WhoLastModifiedPhoto")
	public Integer getWhoLastModifiedPhoto() {
		return this.whoLastModifiedPhoto;
	}

	public void setWhoLastModifiedPhoto(Integer whoLastModifiedPhoto) {
		this.whoLastModifiedPhoto = whoLastModifiedPhoto;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Mobile1")
	public String getMobile1() {
		return this.mobile1;
	}

	public void setMobile1(String mobile1) {
		this.mobile1 = mobile1;
	}

	@Column(name = "Mobile2")
	public String getMobile2() {
		return this.mobile2;
	}

	public void setMobile2(String mobile2) {
		this.mobile2 = mobile2;
	}

	@Column(name = "PhoneInt")
	public String getPhoneInt() {
		return this.phoneInt;
	}

	public void setPhoneInt(String phoneInt) {
		this.phoneInt = phoneInt;
	}

	@Column(name = "PhoneExt")
	public String getPhoneExt() {
		return this.phoneExt;
	}

	public void setPhoneExt(String phoneExt) {
		this.phoneExt = phoneExt;
	}

	@Column(name = "Pager")
	public String getPager() {
		return this.pager;
	}

	public void setPager(String pager) {
		this.pager = pager;
	}

	@Column(name = "MobileCorp")
	public String getMobileCorp() {
		return this.mobileCorp;
	}

	public void setMobileCorp(String mobileCorp) {
		this.mobileCorp = mobileCorp;
	}

	@Column(name = "Fax")
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "Internet")
	public String getInternet() {
		return this.internet;
	}

	public void setInternet(String internet) {
		this.internet = internet;
	}

	@Column(name = "R3Access")
	public String getR3access() {
		return this.r3access;
	}

	public void setR3access(String r3access) {
		this.r3access = r3access;
	}

	@Column(name = "Garant")
	public String getGarant() {
		return this.garant;
	}

	public void setGarant(String garant) {
		this.garant = garant;
	}

	@Column(name = "DomainName")
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	@Column(name = "BWaccess")
	public String getBwaccess() {
		return this.bwaccess;
	}

	public void setBwaccess(String bwaccess) {
		this.bwaccess = bwaccess;
	}

	@Column(name = "Modem")
	public String getModem() {
		return this.modem;
	}

	public void setModem(String modem) {
		this.modem = modem;
	}

	@Column(name = "HRRUPAccess")
	public String getHrrupaccess() {
		return this.hrrupaccess;
	}

	public void setHrrupaccess(String hrrupaccess) {
		this.hrrupaccess = hrrupaccess;
	}

	@Column(name = "EmailPrivate")
	public String getEmailPrivate() {
		return this.emailPrivate;
	}

	public void setEmailPrivate(String emailPrivate) {
		this.emailPrivate = emailPrivate;
	}

	@Column(name = "FP3Access")
	public String getFp3access() {
		return this.fp3access;
	}

	public void setFp3access(String fp3access) {
		this.fp3access = fp3access;
	}

	@Column(name = "FW3Access")
	public String getFw3access() {
		return this.fw3access;
	}

	public void setFw3access(String fw3access) {
		this.fw3access = fw3access;
	}

	@Column(name = "StatePositionText")
	public String getStatePositionText() {
		return this.statePositionText;
	}

	public void setStatePositionText(String statePositionText) {
		this.statePositionText = statePositionText;
	}

	@Column(name = "OrgUnityText")
	public String getOrgUnityText() {
		return this.orgUnityText;
	}

	public void setOrgUnityText(String orgUnityText) {
		this.orgUnityText = orgUnityText;
	}

	@Column(name = "SearchContentField")
	public String getSearchContentField() {
		return this.searchContentField;
	}

	public void setSearchContentField(String searchContentField) {
		this.searchContentField = searchContentField;
	}

	@Column(name = "uID", nullable = false)
	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	@Column(name = "AbsentName")
	public String getAbsentName() {
		return this.absentName;
	}

	public void setAbsentName(String absentName) {
		this.absentName = absentName;
	}

	@Column(name = "LastModifiedSource")
	public Integer getLastModifiedSource() {
		return this.lastModifiedSource;
	}

	public void setLastModifiedSource(Integer lastModifiedSource) {
		this.lastModifiedSource = lastModifiedSource;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModified", length = 23)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "PhotoName")
	public String getPhotoName() {
		return this.photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "Saved")
	public Integer getSaved() {
		return this.saved;
	}

	public void setSaved(Integer saved) {
		this.saved = saved;
	}

}
